name: Backup DynamoDB
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Get today's date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Backup Dynnamo DB
        run: |
          aws dynamodb scan --table-name zonebot_installs --output json > backup-${{ env.DATE }}.json
          aws s3 cp backup-${{ env.DATE }}.json s3://zonebot-dynamo-db-backup/backup-${{ env.DATE }}.json

      # - name: Restore Dynnamo DB
      #   run: |
            # aws s3 cp s3://your-bucket-name/backup.json backup.json
            # aws dynamodb batch-write-item --request-items file://backup.json