name: Deploy to S3 and Trigger Amplify Redeploy

on:
  push:
    branches:
      - main  # or any branch you want to trigger this on

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      # Upload files to S3
      - name: Upload files to S3
        run: |
          ls -la
          zip -r deployment.zip . -x ".git*" 
          aws s3 cp deployment.zip s3://zonebot-website/
      
      # Trigger AWS Amplify redeploy
      - name: Trigger Amplify Redeploy
        run: |
          aws amplify start-deployment \
            --app-id d2ho4ti02h7xe2 \
            --branch-name staging \
            --source-url s3://zonebot-website/deployment.zip
